sudo: false
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
# export GPG details
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
- mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
- mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
- export secretstore_project_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')
deploy:
- provider: script
  skip_cleanup: true
  script: mvn clean deploy --settings .maven.xml -B -U -Prelease
  on:
    tags: true
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "EtMbS+/TfySNtYfUMGBlBFaL0eyEH5QNRYV6Z2Wi4oj5yfrxgyQnkPh7n6bePvQe47n6b53gzsJAkMwP7P4YKLkiFxYv1K/Zm1uJBDyWQdytFtttUUzvnVwHGD6aOnnU5Z4t3va5HGRMXMiWIRVfgtSre/vZY12HD1T3PVipa9ZUVaxaJ7ZJrkuBuyXJUwr4rEiMgy5H2NCTlWw0Iy8/IE3DkYt8mnojo5WjP8LrdjtA7ZDwb9pvHTbI13ASek3xwO/Paq1uOQ/aA/b8XIE2zeTZ1l+s8zR38+hScyY6yIyR2ljbbzOZivaJACMLtr3VB75Z4sS86T2xBjsix1Byw4GErDvJPRlCFQLpW/CViK+zdpfpB+mDmZh0Af8/PV+ukVOpW/K94Cjbze5LUA6vgM23hpdJQIyspLWEeAyodudAsAaC3L+GLwmL+AUljlD+RB0kAbc0rRGwig63MpsVe3zOWZlmDc97t7XzJ7d1Hn2zgTz0ueAMR2DltAej1WOBTU9Ah2+jx4lIVPgiB/XYl3oQremxB2/Qws79gdHB7Eb/HB/yFKaM6JIR60QEuZ6K/8IFyuGkmUxPVu7eaQwCU9gS+LgyTb9R86EQaT17lVzmr627/fxFL4VeDhBamzS18mMAaGsQrmP1okkwgAH6cefLmdveElIrptF258iimzw="
  file:
  - target/secret-store-client-$secretstore_project_version.jar
  name: "$secretstore_project_version"
  on:
    tags: true
    all_branches: true

