sudo: false
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
# export GPG details
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
- mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
- mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
- export secretstore_project_version=$(mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]')
deploy:
- provider: script
  skip_cleanup: true
  script: mvn clean deploy --settings .maven.xml -B -U -Prelease
  on:
    tags: true
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "Ms2kbCPHyNvRR8Vh9Ik6EX1E6oL/gQs8yDHnCzOH8V9WE0E9C2B9biIKBRdCYRkubrl+8HwRUpuUS2gzkCypDPcnpFQ3V2y6gjO60yvYfwQ0u5p+b4PQ7XwSpahPafv8578+59NmZI55yMdowcedzZGetwoz6B/ONkePt/mdVUJL0P8Hftafse5/XnUDg38Qhqpu22KzAbTToUlaxUmoqCKzfTrkmO5FrN1IYQ/6GMizDn+luYBEjcNQIPaLSFATfl/ubUTtzDfPs1lxbe7biNWGZZDcZk6FweNzxQq1F68gBW5shFfl/KP6MRl8cfULK6bN89KTrz0/V+/zTnA1S+KsZv34cxuPEXahSK36wsxR3KYTGwZbctKJSCDHHMqw7DxpGz/m1ETIWpsExAwAGhUo9vFbv3Mwv8iWyopU8lyFr1LIxqgpc5ccWhzcoupbt8c7isei9Cc7aoxWwN+N/9Py2rRk2lZh8vkKS3SINJkyOBPHeHSN893Dev1n9JVEY0MUJivIeoT7uS+43MtAG5itIDJCMvllNkK/jvbTt7RzPqeF++lLCBKWZHRt7nSMrSPqrlvRJRmq8wb+0MtXRP2ZVVFQIrLHhJRIUJDBC5KsQl6ZWDS0PSX0x9oBrGAdD5iOb8oKQCQxlFXg79b1rI02xNAyhTDSPbAdXCMtSJI="
  file:
  - target/secret-store-client-$secretstore_project_version.jar
  name: "$secretstore_project_version"
  on:
    tags: true
    all_branches: true

