sudo: false
language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
install:
- mvn --settings .maven.xml install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
- mvn help:evaluate -Dexpression=project.version | grep -e '^[^\[]'
- export secretstore_project_version=$(mvn help:evaluate -Dexpression=project.version
  | grep -e '^[^\[]')
deploy:
- provider: script
  skip_cleanup: true
  script: mvn clean deploy --settings .maven.xml -B -U -Prelease
  on:
    tags: true
    all_branches: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: kCjVvKfZ49O452+S8JOt248MyjVFD6tSUIs3+9BPWGEzT8yeIyt8940MEE0R7zLq86fQy4fKeGbm2hG928T3bBecuCVsRl+ZTYZkCQk0hthGmL0+IbZPxUm/+ExRTDF5LBwidyBif7YUL2jehwJmrFXxACyQFdQKrYiNKCRnknk69xc/wwzaQpb6YadoXSFhIxhS5tYSni0/2Ku0R5SGScyBDGuxjKyBB0WUGbBxaxSKOX5gcz+87FNekFz+vZdrrCF4pvdgO0d2EFhkMJAdm1WywnI0mhYDSD668EYhCL0n++B8N8T5tCo3RIdPe5JhK4rNG59kV0O/i/S+A+87+AE/VNDoYjVFJMVfL6zXZO3z9lS5arScujJZzAyyR3noF7VE1WHNaTo6uoirGtsDW7BcqIAs4itTT/4YSLSKZEIx2ZtNAvhwfJhPDBYpPbesx2I7Y9ChNzPAcSXuMf4OUZIiflHgVhS0NUmZrT/ysr7qxhv7IwETMwBzCl2c2VSBb5Uy3cuwRErMumw5sv3o4h0d3p9ejFNHUcyEk72YX+pNooxGhTO7yvosnVBevj/QblWzSp+RMqJWvK7lLJjFsg/vyCHFmGGodJoRNH7px2GEZ1hNPFfC89dMb3zRQl/IfCol+oOho0NE3thbN2qkUHt7jigeVGjdK7EJqTwn46U=
  file: target/secret-store-client-$secretstore_project_version.jar
  on:
    repo: oceanprotocol/secret-store-client-java
    tags: true
    all_branches: true
